### ISSUE TITLE
Make a simplified CLI

### ISSUE THREAD

**Issue by rob-clarke** [StarlingUAS/Murmuration#2]
It would be nice to abstract out all the docker/kubernetes stuff so we have a cleaner interface.

Something like:

```
$ starling vehicle list
clover23 (px4)
qav36 (apm)

$ starling deploy ./my_controller --vehicle clover23
'my_controller' deployed on clover23

$ starling controller list
my_controller (running on clover23)

$ starling start
Controllers started...

$ starling stop
Landing all vehicles...

$ starling kill
Emergency stopping all vehicles...
```

**Comment by mhl787156** [comment]
With https://github.com/StarlingUAS/ProjectStarling/pull/116, the movement of kubernetes script to murmuration, it offers a good opportunity to start creating a simple cli for a few basic operations:

- [ ] initial kubectl installation (with sudo)
- [ ] applying a particular configuration file
- [ ] deleting a particular configuration file
- [ ] starting n vehicles in simulation

**Comment by mhl787156** [comment]
- [ ] add dynamic starting with user configurable number of nodes
